//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDevs.TPV
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesDetalles
    {
        public int Codigo_Orden_Detalle { get; set; }
        public int Codigo_Orden { get; set; }
        public int Codigo_Producto { get; set; }
        public Nullable<int> Codigo_Producto_Unidad_Medida { get; set; }
        public int Cantidad_Producto { get; set; }
        public Nullable<int> Codigo_Producto_Extra { get; set; }
        public decimal? Sub_Total_Precio_Producto { get; set; }
        public Nullable<int> Cantidad_Personas { get; set; }
        public string Nota_Producto { get; set; }
        public System.DateTime Hora_Orden_Detalle { get; set; }
        public int Codigo_Estado_Orden_Detalle { get; set; }
        public int Codigo_Usuario { get; set; }
        public bool Activo { get; set; }
    
        public virtual EstadosOrdenDetalle EstadosOrdenDetalle { get; set; }
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Productos Productos1 { get; set; }
        public virtual ProductosUnidadesMedidas ProductosUnidadesMedidas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
