//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDevs.TPV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.OrdenesDetalles = new HashSet<OrdenesDetalles>();
        }
    
        public int Codigo_Orden { get; set; }
        public int Codigo_Mesa { get; set; }
        public int Comensales { get; set; }
        public System.DateTime Hora_Orden { get; set; }
        public int Codigo_Estado_Orden { get; set; }
        public Nullable<int> Codigo_Metodo_Pago { get; set; }
        public Nullable<System.DateTime> Hora_Pago { get; set; }
        public bool Activo { get; set; }
    
        public virtual EstadosOrden EstadosOrden { get; set; }
        public virtual Mesas Mesas { get; set; }
        public virtual Metodos_Pago Metodos_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesDetalles> OrdenesDetalles { get; set; }
    }
}
