//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDevs.TPV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosUnidadesMedidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosUnidadesMedidas()
        {
            this.OrdenesDetalles = new HashSet<OrdenesDetalles>();
        }
    
        public int Codigo_Producto_Unidad_Medida { get; set; }
        public int Codigo_Producto { get; set; }
        public int Codigo_Unidad_Medida { get; set; }
        public decimal Precio_Venta { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesDetalles> OrdenesDetalles { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas { get; set; }
    }
}
