//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDevs.TPV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.OrdenesDetalles = new HashSet<OrdenesDetalles>();
            this.OrdenesDetalles1 = new HashSet<OrdenesDetalles>();
            this.ProductosUnidadesMedidas = new HashSet<ProductosUnidadesMedidas>();
        }
    
        public int Codigo_Producto { get; set; }
        public int Codigo_Categoria_Producto { get; set; }
        public string NombreProducto { get; set; }
        public byte[] ImagenProducto { get; set; }
        public decimal PrecioVenta { get; set; }
        public int OrdenProducto { get; set; }
        public int Codigo_Tipo_Producto { get; set; }
        public Nullable<decimal> PrecioComoExtra { get; set; }
        public bool AceptaExtra { get; set; }
        public bool Impresora { get; set; }
        public bool Activo { get; set; }
    
        public virtual CategoriasProductos CategoriasProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesDetalles> OrdenesDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesDetalles> OrdenesDetalles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosUnidadesMedidas> ProductosUnidadesMedidas { get; set; }
        public virtual TiposProductos TiposProductos { get; set; }
    }
}
